name: Python application

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2

    - name: Set up Python 3.9 environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install SQLite
      run: sudo apt-get install -y sqlite3

    - name: Set up test environment
      run: |
        mkdir -p test
        touch test/LibraryTest.db

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest
